### ISSUE TITLE
Having trouble implementing sitemapconfig on dotnet core.

### ISSUE THREAD

**Issue by johnbie** [wintoncode/Winton.AspNetCore.Seo#26]
I'm using an MVC routing method, which is defined in configure method of startup. I don't know how to implement MyImplementationOfISitemapConfig object for ConfigureServices on startup. Do I need to create a separate class? Can I use ISiteConfig object as is? And how do I create an array of SitemapConfigUrls?

**Comment by johnbie** [comment]
Actually, I created a separate SiteConfig file in the same directory as Startup, and am adding a list of SitemapConfigUrl to Urls. How do I create a list of relative/parameter-based paths? I don't want to add a separate link for every single item for each page that fit the "{controller=Home}/{action=Index}/{id?}" template.

**Comment by Choc13** [comment]
Hi @johnbie,

Sorry for the slow reply, I've been away on holiday.

It sounds like you figured out that the intention is to create your own implementation of [`ISitemapConfig`](https://github.com/wintoncode/Winton.AspNetCore.Seo/blob/master/src/Winton.AspNetCore.Seo/Sitemaps/ISitemapConfig.cs).

The reason there is no default implementation of this is because it was not clear to me when creating the library that there is a single obvious way to provide such an implementation that most applications would find useful. Therefore, we deliberately chose to leave the implementation up to the user so they could decide the best way to generate the sitemap data that would drive be rendered as a `sitemap.xml` file. 

The typical use case for us is to define a POCO `SitemapConfig` class which is populated from the application's configuration. For instance by binding a section of the `IConfiguration` to that class. I can see how in the MVC case however it would be useful to have the `ISitemapConfig` driven from the defined routes. You might have already seen this in the README, but it is possible to call `services.AddSeo<TSitemapConfig>();` in order to add the SEO services in your `Startup.cs` class. In this case you can pass any type that implements `ISitemapConfig` and it will be resolved at runtime. In this way it is possible to inject other services into your implementation of `ISitemapConfig`. For example you could inject [`IActionDescriptorCollectionProvider`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.infrastructure.iactiondescriptorcollectionprovider?view=aspnetcore-2.1) and use that to figure out which routes have been registered with MVC in your application. I am unsure of the exact details, but at least at a high level it feels like it should be possible for you to create an implementation of `SitemapConfig` that generates its `Urls` property by consuming an ASP.NET Core MVC service and enumerating all of the registered routes. I suppose this would depend on whether or not your were able to also enumerate all of the parameters if any of the paths are parameterised in your MVC routes. 

If you are able to make this work, then I think it would make for a good addition to this library. For example if we called it something like `MvcSitemapConfig` then others could optionally chose to use it by called `services.AddSeo<MvcSitemapConfig>();`.

**Comment by Choc13** [comment]
This [GitHub issue](https://github.com/aspnet/Mvc/issues/6330) and this [Stack Overflow post](https://stackoverflow.com/questions/41908957/get-all-registered-routes-in-asp-net-core) might be of interest to you. Also the [`RouteCollection`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.routing.routecollection?view=aspnetcore-2.1) class could come in handy when trying to dynamically generate a list of registered MVC routes.

**Comment by Choc13** [comment]
I'm going to close this issue as it doesn't appear to relate to a bug. If there are any further questions or you do end up implementing some code that generates a `SitemapConfig` from MVC routes and would like to contribute back, then feel free to re-open this issue.
